spring:
  application:
    name: "helloworld"

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
